# HTTP
quarkus.http.port=8080
quarkus.http.cors=true

# Logs
quarkus.log.level=INFO
quarkus.log.category."com.formation".level=DEBUG

# Datasource PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5436/bookswap_db

# Hibernate ORM
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

# D�sactiver les Dev Services (on g�re PostgreSQL manuellement)
quarkus.devservices.enabled=false

# JWT Configuration
mp.jwt.verify.publickey.location=/keys/publicKey.pem
mp.jwt.verify.issuer=https://exchange-manager-api.com
smallrye.jwt.sign.key.location=/keys/privateKey.pem
jwt.expiration.time=3600
jwt.refresh.expiration.time=604800

# Base de donn�es H2 pour les tests (en m�moire)
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;MODE=PostgreSQL
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.log.sql=false

# D�sactiver les Dev Services
%test.quarkus.datasource.devservices.enabled=false

# JWT pour les tests (m�me issuer que la config principale)
%test.mp.jwt.verify.issuer=https://exchange-manager-api.com